### ISSUE TITLE
Support for Advanced Monitors

### ISSUE THREAD

**Issue by Nick1st** [Pyroxenium/Basalt#10]
Does this have support for advanced monitors?

**Comment by Nick1st** [comment]
Like, I mean not everything of course, but stuff like buttons, dropdowns, etc...

**Comment by Nick1st** [comment]
Thanks for your reply. Would you mind sending me the program (via pastebin or such)?

**Comment by NoryiE** [comment]
Hello,

officially basalt doesn't support monitors right now. But, thats something which will change soon. However, Erb3's solution would work to solve the issue for now. 

I promise, monitor support is something i will add soon.

**Comment by NoryiE** [comment]
Hello, basalt officially supports monitors now. But monitors do ignore keyboard events. There is a trick if you need this feature, but i wont add it officially - atleast for now.
