### ISSUE TITLE
feature: Custom colors

### ISSUE THREAD

**Issue by zambony** [Pyroxenium/Basalt#110]
It seems we're limited to using the standard colors provided by the `colors` library. Using colors created with `colors.packRGB` results in an error, as the color lookup in the `tHex` library fails. I'd Like to be able to use custom colors for gradients in heat graphs and darkening buttons when clicked.

Are there plans to support custom colors, and is this even supported by the monitors?

**Comment by NoryiE** [comment]
Hi, CC:Tweaked is only able to show 16 colors at a time, basalt is also limited to that. The only way to change colors is by editing the current color palette: https://tweaked.cc/module/term.html#v:setPaletteColour

**Comment by zambony** [comment]
Ah, I guess I missed that. That's a shame. Thanks.
