### ISSUE TITLE
bug: [TITLE]“onEvent”disable

### ISSUE THREAD

**Issue by Dawekis** [Pyroxenium/Basalt#111]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Checklist**

[ ] I am running the latest version.
Tick the box if you are running the latest version!

**Comment by Dawekis** [comment]
I want use "onEvent" to create custom events, but, no effect, even following the case on the wiki.

**Comment by Dawekis** [comment]
![{EC0602C6-CBB1-4250-BE7F-B731E314C5D3}](https://github.com/Pyroxenium/Basalt/assets/115648743/07b5ea4c-b125-4895-acda-6bdde3899bc5)

**Comment by NoryiE** [comment]
I've tested it and everything seems to work. Are you sure you are sending rednet events? Also if you want you can try

```lua
basalt.onEvent(function(event, side, ...)
basalt.debug(event)
end)
```
This should also work.

**Comment by Dawekis** [comment]
Thanks of NoryiE!
