### ISSUE TITLE
On the dev branch of basalt os.pullEvent in threads doesn't support filters

### ISSUE THREAD

**Issue by MasonGulu** [Pyroxenium/Basalt#34]
**Describe the bug**

When you use os.pullEvent in a thread the filter is ignored.

**To Reproduce**

```lua
local basalt = require("basalt")

local main = basalt.createFrame():setTheme({FrameBG = colors.lightGray, FrameFG = colors.black})
local thread = main:addThread()
thread:start(function()
  while true do
    print(textutils.serialize({os.pullEvent("key_up")}))
  -- Now I'm not sure if this code would work
  -- Just because the basalt event handler isn't running when I try to start this thread
  -- but my point still stands
  -- if it does work, this will error. It will instead catch one of the basalt events, one that has functions in the table returned therefor crashing the program.
  end
end)

basalt.autoUpdate()
```

**Expected behavior**

The example above wouldn't crash, because it would only ever resume on "key_up" events

**Screenshots**
N/A

**Additional context**
N/A

**Checklist**

[ ] I am running the latest version.
Tick the box if you are running the latest version!

I am running the DEV branch, from when you told me to update it

**Comment by NoryiE** [comment]
Thank you, i actually really forgot to add filters for threads, i will implement it this weekend.

**Comment by NoryiE** [comment]
Hello the missing filters for threads got added in [153f082](https://github.com/Pyroxenium/Basalt/commit/153f08244c2486a51e179d5dcb42830498ec414d) - currently only available in the dev branch.
