### ISSUE TITLE
bug: XML number buttons crash Basalt

### ISSUE THREAD

**Issue by big-duckie** [Pyroxenium/Basalt#44]
**Describe the bug**

When using buttons in XML, if the text is set to only numbers, Basalt crashes. This bug only happens when you create buttons via XML.
If the text field has any non-numeric character the bug doesn't happen.

**To Reproduce**

1. Create a XML layout with a button with the text "123"
2. Add this layout to a frame.
3. Run.
4. Crash.

**Expected behavior**

It should just show the numbers, as it does when you programmatically create a button.

**Checklist**

[x] I am running the latest version.
Tick the box if you are running the latest version!

**Comment by NoryiE** [comment]
Helloo! I think it's fixed now. Thank you very much for the report.
