### ISSUE TITLE
docs: Latest 1.7 docs suggests their is a `Basalt.setTheme()`

### ISSUE THREAD

**Issue by ajh123** [Pyroxenium/Basalt#54]
** Where? **
https://github.com/Pyroxenium/Basalt/blame/d4c72514ef560af88c7f7557ba6f35ddaa2dc724/docs/objects/Basalt.md#LL29C45-L29C45

As the title says, the docs contain a `Basalt.setTheme()` function which appears to no longer exist.
When I load Basalt and run the `Basalt.setTheme()` from the Lua prompt (or any other file) I get the following error (even if I pass a correct table):
![basalt_error](https://user-images.githubusercontent.com/41990982/235648338-9b365c8c-95a8-4756-a299-6fe8b0998e06.PNG)

** Possible solutions **
1. Remove the function from the docs.
2. Update the docs to contain the new alternative.
3. Resurrect the old `setTheme()` function.

** Others **
I have downloaded the recent `Minified/Packed Version` a few minutes ago.

** Checklist **
[ X ] I am looking at the latest version of the docs.

**Comment by NoryiE** [comment]
Hello and thank you! I made a small mistake in my code which made setTheme and getTheme not public. Also fixed a small bug when using themes. This is fixed here: [6c235b0](https://github.com/Pyroxenium/Basalt/commit/6c235b04dfe772205281b477eb0425210bf98b35)

**Comment by ajh123** [comment]
Yes, that worked now.
