### ISSUE TITLE
bug: installer errors

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [Pyroxenium/Basalt#91]
### What happened?

A while after running `pastebin run ESs1mg7P packed`, whilst the installer is running, the following error occurs:
![image](https://github.com/Pyroxenium/Basalt/assets/38588376/1998f437-af7f-4d9c-a38e-ee014468dd9a)

### Computercraft client

Ingame (Default)

### Relevant log output

```shell
N/A
```

### Latest Basalt Version

- [X] I use the latest stable version

**Comment by NoryiE** [comment]
Hey! Where did you get this Installer Command from? Because the pastebin command is outdated. This is the new way to install basalt: wget run https://basalt.madefor.cc/install.lua packed

**Comment by ThatBlockyPenguin** [comment]
Ah, I found it on the ComputerCraft wiki. Thanks, I'll use that one! :)

**Comment by ThatBlockyPenguin** [comment]
And that worked. Thanks!
